# 配置

# 12306账号密码配置（暂时没用到）
j12306:
  user: 182xxxx
  password: 123456

  ticket:
    queryspeed: 2000 # 刷票速度（单位毫秒）。默认2秒。官网放票前1分钟修改（50~100毫秒左右可大大增加抢到票概率，但是不能以这个速度刷太长时间，避免封IP）温馨提示：刷票频率不要过快，避免封IP（暂未测试过）
    alternate: false # 开启自动候补
    queryp: Z # 查票默认接口（可选值：A、Z）。说明：由于12306官方查票接口经常在A和Z两个接口中变更，所以为了方便，在此处加了默认接口配置。
    puttime: 13-00  # 12306放票时间点，格式(HH-mm)（作用看下面puttimespeed的说明）。如果不需要可以配置为 null
    puttimespeed: 100 # 放票点刷票速度（单位毫秒）。在12306放票时间点前1分钟程序会自动把刷票速度切换到这个速度（因为只是短时间内提高刷票速度，避免了封IP）

  # 通知配置
  notice:
    # 电子邮件配置
    email:
      sender:
        from: hutool@yeah.net   # 发件人（必须正确，否则发送失败）
        host: smtp.yeah.net    # 邮件服务器的SMTP地址，可选，默认为smtp.<发件人邮箱后缀>
        port: 25    # 邮件服务器的SMTP端口，可选，默认25
        user: hutool    # 用户名
        pass: qlw2e3    # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
      receiver: 1481397688@qq.com   # 接收人邮箱